[package]
name = "javy"
version = "0.1.0"
authors = ["Saúl Cabrera <saulecabrera@gmail.com>"]
edition = "2018"
build = "build.rs"

[[bin]]
name = "javy"

[dev-dependencies]
wasmtime = "0.27.0"
wasmtime-wasi = "0.27.0"
serde = "1.0.126"
serde_json = "1.0.64"
rmp-serde = "0.15.5"
rmpv = {version = "0.4.7", features = ["with-serde"]}
proptest = "1"

[dependencies]
wizer = "1"
structopt = "0.3"
anyhow = "1.0"
tempfile = "3.2.0"
dirs = "1.0.5"
