[package]
name = "javy-core"
version = "0.1.0"
authors = ["Saúl Cabrera <saulecabrera@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0"
quickjs-sys = { path = "../quickjs-sys" }
serde = { version = "1.0.123", default-features = false }
serde-transcode = "1.1.0"
rmp-serde = "^0.15"
wee_alloc = "0.4.5"

[dev-dependencies]
quickcheck = "1"

[profile.release]
lto = true
opt-level = 3

[features]
standalone-wasi = []
